meisterplan/helm-charts

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/post-deployment/prometheus-rules.yaml
charts/spring-service/values.yaml
tests/spring-service/simple-service/expected/spring-service/templates/post-deployment/prometheus-rules.yaml
tests/spring-service/simple-service/values.yaml

Add new mandatory parameter playbook_url for alertingRules

---

charts/spring-service/values.yaml

- chart uses another name, will not fit if copied and uncommented
KNUTH-51936

Fix outdated variable naming

---

CHANGELOG.md
charts/spring-service/templates/post-deployment/ingress.yaml
charts/spring-service/templates/pre-deployment/secret.yaml
tests/spring-service/simple-service/expected/spring-service/templates/post-deployment/ingress.yaml
tests/spring-service/simple-service/expected/spring-service/templates/pre-deployment/secret.yaml
tests/spring-service/simple-service/values.yaml

Add ingress basicAuthSecretParameterName

---

CHANGELOG.md
charts/cronjob/templates/cronjob.yaml
charts/cronjob/values.yaml
tests/cronjob/simple-cronjob/expected/cronjob/templates/cronjob.yaml
tests/cronjob/simple-cronjob/values.yaml

- will not add a new version, should
be backwards compatible.

Add functionality for args of cronjob

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/pre-deployment/pod-monitor.yaml
charts/spring-service/values.yaml

Add option to disable prometheus scrape

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
charts/spring-service/templates/post-deployment/service.yaml
charts/spring-service/values.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/post-deployment/service.yaml
tests/spring-service/simple-service/values.yaml

KNUTH-53100 Einfach machen

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
charts/spring-service/values.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/values.yaml

Replace initial delay with startupProbe, make failAfterCount configurable

---

CHANGELOG.md
Makefile
charts/cronjob/Chart.yaml
charts/cronjob/templates/post-deployment/prometheus-rules.yaml
tests/cronjob/simple-cronjob/expected/cronjob/templates/post-deployment/prometheus-rules.yaml
tests/cronjob/simple-cronjob/values.staging.yaml
tests/cronjob/simple-cronjob/values.yaml

- add new option to add Prometheus Rules
for Cronjobs
KNUTH-53444

Add AlertingRules for Cronjobs as well

---

CHANGELOG.md
charts/cronjob/Chart.yaml
charts/cronjob/templates/post-deployment/prometheus-rules.yaml
charts/spring-service/Chart.yaml
charts/spring-service/templates/post-deployment/prometheus-rules.yaml
charts/spring-service/values.yaml
tests/cronjob/simple-cronjob/expected/cronjob/templates/post-deployment/prometheus-rules.yaml
tests/cronjob/simple-cronjob/values.staging.yaml
tests/spring-service/simple-service/expected/spring-service/templates/post-deployment/prometheus-rules.yaml
tests/spring-service/simple-service/values.yaml

KNUTH-51982 Chart anpassen, Alerts ändern und Operator anpassen

---

CHANGELOG.md

see kubernetes/ingress-nginx/issues/6962

Put a big fat warning on v2.2.1 due to 503 "No active endpoints"

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
charts/spring-service/templates/pre-deployment/secret.yaml
tests/spring-service/simple-service-rls/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service-rls/expected/spring-service/templates/pre-deployment/secret.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/pre-deployment/secret.yaml

Add support to change RabbitMQ ssl enabled flag

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
tests/spring-service/complex-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml

Add additional pull secret to deployment

---

charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
tests/spring-service/complex-service/expected/spring-service/templates/deployment.yaml

Add flyway url to ensure it works with tracing enabled

---

Makefile

Add check in test whether CHANGELOG was updated for new version

---

CHANGELOG.md
Makefile
charts/cronjob/Chart.yaml
charts/cronjob/templates/cronjob.yaml
charts/cronjob/templates/pre-deployment/serviceaccount.yaml
tests/cronjob/service-account-cronjob/expected/cronjob/templates/cronjob.yaml
tests/cronjob/service-account-cronjob/expected/cronjob/templates/post-deployment/prometheus-rules.yaml
tests/cronjob/service-account-cronjob/expected/cronjob/templates/pre-deployment/secret.yaml
tests/cronjob/service-account-cronjob/expected/cronjob/templates/pre-deployment/serviceaccount.yaml
tests/cronjob/service-account-cronjob/values.staging.yaml
tests/cronjob/service-account-cronjob/values.yaml

KNUTH-76836 Apolloalpaca Schema sync zu Rolle umziehen

---

CHANGELOG.md
charts/cronjob/Chart.yaml
charts/cronjob/templates/pre-deployment/secret.yaml
charts/cronjob/values.yaml
charts/spring-service/Chart.yaml
charts/spring-service/templates/pre-deployment/secret.yaml
charts/spring-service/values.yaml
tests/cronjob/service-account-cronjob/expected/cronjob/templates/pre-deployment/secret.yaml
tests/cronjob/service-account-cronjob/values.yaml
tests/cronjob/simple-cronjob/expected/cronjob/templates/pre-deployment/secret.yaml
tests/cronjob/simple-cronjob/values.yaml
tests/spring-service/complex-service/expected/spring-service/templates/pre-deployment/secret.yaml
tests/spring-service/complex-service/values.yaml
tests/spring-service/simple-service/expected/spring-service/templates/pre-deployment/secret.yaml
tests/spring-service/simple-service/values.yaml

KNUTH-78681
[KNUTH-78681]: https://itdesign-de.atlassian.net/browse/KNUTH-78681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KNUTH-78681 Helm Chart anpassen

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
tests/spring-service/complex-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml

- yml structures will change... reflect in a backwards compatible way in the chart.
KNUTH-87508

Add config settings for Sprint Boot 3

---

charts/spring-service/templates/deployment.yaml
tests/spring-service/complex-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml

Enable tracing via spring profile

---

charts/spring-service/templates/deployment.yaml
tests/spring-service/complex-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml

KNUTH-88313 Tracing geht nicht

---

charts/spring-service/templates/deployment.yaml
charts/spring-service/templates/pre-deployment/secret.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/pre-deployment/secret.yaml

KNUTH-90281 TrialToucan BootLoop wegen SQL

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
tests/spring-service/complex-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml

Add topologySpreadConstraints to distribute evenly over AZs

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
tests/spring-service/complex-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml

KNUTH-102292 Topology-Spread does not work

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/values.yaml
tests/spring-service/complex-service/expected/spring-service/templates/deployment.yaml

KNUTH-102287 Fix Container Startup Issues

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
tests/spring-service/complex-service/expected/spring-service/templates/deployment.yaml
tests/spring-service/simple-service/expected/spring-service/templates/deployment.yaml

Enable OpenTelemetry via gRPC

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/pre-deployment/extra-mainfests.yaml
charts/spring-service/values.yaml
tests/spring-service/complex-service/expected/spring-service/templates/pre-deployment/extra-mainfests.yaml
tests/spring-service/complex-service/values.yaml

Allow additonal manifests to be provided with chart

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/post-deployment/ingress-public.yaml
tests/spring-service/complex-service/expected/spring-service/templates/post-deployment/ingress-public.yaml
tests/spring-service/simple-service/expected/spring-service/templates/post-deployment/ingress-public.yaml

KNUTH-113613 Neuen Ingress "-public" im Helm-Chart anlegen

---

CHANGELOG.md
Makefile
charts/cronjob/Chart.yaml
charts/cronjob/templates/cronjob.yaml
charts/cronjob/templates/pre-deployment/secret.yaml
charts/cronjob/templates/pre-deployment/serviceaccount.yaml
charts/cronjob/values.yaml
charts/spring-service/templates/deployment.yaml
charts/spring-service/templates/post-deployment/_helpers.tpl
charts/spring-service/templates/post-deployment/ingress-public.yaml
charts/spring-service/templates/pre-deployment/secret.yaml
charts/spring-service/templates/pre-deployment/serviceaccount.yaml
charts/spring-service/values.yaml
tests/cronjob/service-account-cronjob/expected/cronjob/templates/pre-deployment/serviceaccount.yaml
tests/cronjob/service-account-cronjob/values.staging.yaml
tests/cronjob/service-account-cronjob/values.yaml
tests/cronjob/simple-cronjob/values.yaml
tests/spring-service/complex-service/expected/spring-service/templates/post-deployment/ingress-public.yaml
tests/spring-service/complex-service/values.yaml
tests/spring-service/simple-service/expected/spring-service/templates/post-deployment/ingress-public.yaml
tests/spring-service/simple-service/values.yaml

KNUTH-113595 Service Helm-Chart anpassen (Major Version)

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/post-deployment/ingress-public.yaml
tests/spring-service/complex-service/expected/spring-service/templates/post-deployment/ingress-public.yaml
tests/spring-service/complex-service/values.yaml

KNUTH-114183 Cut new helm-chart with OAuth

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/deployment.yaml
charts/spring-service/templates/post-deployment/_helpers.tpl
charts/spring-service/templates/post-deployment/ingress-public.yaml

spring-service 4.1.1: Fix unexpected issues when no ingress.public.paths

---

CHANGELOG.md
charts/spring-service/Chart.yaml
charts/spring-service/templates/post-deployment/prometheus-rules.yaml
tests/spring-service/simple-service/expected/spring-service/templates/post-deployment/prometheus-rules.yaml
tests/spring-service/simple-service/values.yaml

KNUTH-116206 Support "pint annotation" in helm chart

---

CHANGELOG.md
charts/cronjob/Chart.yaml
charts/cronjob/templates/post-deployment/prometheus-rules.yaml
charts/cronjob/values.yaml
charts/spring-service/Chart.yaml
charts/spring-service/templates/post-deployment/prometheus-rules.yaml
charts/spring-service/values.yaml
tests/cronjob/simple-cronjob/expected/cronjob/templates/post-deployment/prometheus-rules.yaml
tests/cronjob/simple-cronjob/values.yaml
tests/spring-service/simple-service/expected/spring-service/templates/post-deployment/prometheus-rules.yaml
tests/spring-service/simple-service/values.yaml

KNUTH-117805 Update HelmChart to allow setting alert urgency

---

charts/cronjob/Chart.yaml

KNUTH-119288 Update Helm Chart to allow defining severtity

---

CHANGELOG.md
charts/cronjob/Chart.yaml
charts/cronjob/templates/post-deployment/prometheus-rules.yaml
charts/spring-service/Chart.yaml
charts/spring-service/templates/post-deployment/prometheus-rules.yaml
charts/spring-service/templates/pre-deployment/pod-monitor.yaml
tests/cronjob/service-account-cronjob/expected/cronjob/templates/post-deployment/prometheus-rules.yaml
tests/cronjob/simple-cronjob/expected/cronjob/templates/post-deployment/prometheus-rules.yaml
tests/spring-service/complex-service/expected/spring-service/templates/post-deployment/prometheus-rules.yaml
tests/spring-service/complex-service/expected/spring-service/templates/pre-deployment/pod-monitor.yaml
tests/spring-service/simple-service/expected/spring-service/templates/post-deployment/prometheus-rules.yaml
tests/spring-service/simple-service/expected/spring-service/templates/pre-deployment/pod-monitor.yaml

KNUTH-123154 Remove legacy Prometheus Helm tagging on additional resources
